int _putchar(char c);
int print_alphabet();
int print_alphabet_x10();
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int i);
void jack_bauer(void);
int add(int, int);
